import type { Repo } from "../lib/types";

// The org's repositories: every public one, in the order the site shows them,
// each with the role it plays. This list is what the site renders — GitHub
// overlays description, language, stars, issues and push time onto it at build
// time, and a repository missing from here appears nowhere, live or not. The
// committed values are the snapshot a build falls back to when GitHub is
// unreachable, so a build (and local dev without a token) never fails.
//
// The milestone snapshot moved to seed-milestones.ts and the release snapshot
// to seed-releases.ts. Both are re-exported here so an import of either from
// this module keeps resolving.

export { seedMilestones } from "./seed-milestones";
export { seedReleases } from "./seed-releases";

// name, role, language, description — and whatever else that repository has.
// The address follows from the name; the counts start at zero because GitHub
// supplies them.
function seed(
  name: string,
  role: string,
  language: string,
  description: string,
  rest: Partial<Repo> = {},
): Repo {
  return {
    name,
    role,
    language,
    description,
    url: `https://github.com/lemonfiber/${name}`,
    stars: 0,
    openIssues: 0,
    ...rest,
  };
}

export const seedRepos: Repo[] = [
  seed("spec", "canonical", "Markdown", "The canonical specification — every behaviour written down before it is built, and the why behind each one.", { primary: true }),
  seed("lemonfiber", "the binary", "Rust", "The Lemonfiber binary: sets up your media stack, runs it in slices, proves it works. Rust.", { primary: true, latestRelease: "v0.8.0" }),
  seed("lemonfiber-media-stack", "the stack", "Shell", "The Docker Compose stack it orchestrates — 19 services + the stack.toml manifest.", { primary: true }),
  seed("lemonfiber-web", "the web surface", "TypeScript", "The operator console and household view — a static app that draws the binary's API and implements nothing."),
  seed("sdk-ts", "the TypeScript client", "TypeScript", "Typed calls, a typed event stream and a typed error over the local web API."),
  seed("sdk-php", "the PHP client", "PHP", "The same contract implemented as a peer rather than translated."),
  seed("brand", "identity", "CSS", "Logo, colour and type — design tokens with contrast CI."),
  seed("homebrew-tap", "placeholder", "Ruby", "brew install lemonfiber — a formula stub, generated by release CI once Homebrew publishing turns on."),
  seed("website-lemonfiber.app", "this site", "Astro", "This frontpage — a build-in-the-open site driven by the org."),
  seed("website-docs.lemonfiber.app", "the docs", "TypeScript", "docs.lemonfiber.app — the task-shaped documentation, and each repo's own docs pinned and rendered."),
  seed(".github", "inherited", "Markdown", "Community health files, issue templates and the dependency policy every repo inherits."),
];
