name: stale
on:
  schedule:
    - cron: "40 1 * * *"
permissions:
  contents: read

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: lemonfiber/spec/.github/workflows/stale.yml@72472b4a5b35e3edf9a6a539f23f5b0eb528d878 # v1.0.78
