name: stale
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  contents: read

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: lemonfiber/spec/.github/workflows/stale.yml@93bf49c96ae5b12e49daea523b1d66ae294babb0 # main
